### ISSUE TITLE
Evangelism: Weekly Update March 13th

### ISSUE THREAD

**Issue by julianduque** [nodejs/evangelism#41] opened 2015-03-09 21:50 UTC
# io.js 1.5.1 Release

On Monday, March 9th, @rvagg released io.js [v1.5.1](https://iojs.org/dist/v1.5.1/). The complete change log can be found [on GitHub](https://github.com/iojs/io.js/blob/v1.x/CHANGELOG.md).
### Notable changes
- **tls**: The reported TLS memory leak has been resolved via various commits in this release. Current testing indicated that there _may_ still be some leak problems. Track complete progress at [#1075](https://github.com/iojs/io.js/issues/1075).
- **http**: Fixed an error reported at [joyent/node#9348](https://github.com/joyent/node/issues/9348) and [npm/npm#7349](https://github.com/npm/npm/issues/7349). Pending data was not being fully read upon an `'error'` event leading to an assertion failure on `socket.destroy()`. (Fedor Indutny) [#1103](https://github.com/iojs/io.js/pull/1103)
### Known issues
- Possible remaining TLS-related memory leak(s), details at [#1075](https://github.com/iojs/io.js/issues/1075).
- Windows still reports some minor test failures and we are continuing to address all of these as a priority. See [#1005](https://github.com/iojs/io.js/issues/1005).
- Surrogate pair in REPL can freeze terminal [#690](https://github.com/iojs/io.js/issues/690)
- Not possible to build io.js as a static library [#686](https://github.com/iojs/io.js/issues/686)
- `process.send()` is not synchronous as the docs suggest, a regression introduced in 1.0.2, see [#760](https://github.com/iojs/io.js/issues/760) and fix in [#774](https://github.com/iojs/io.js/issues/774)
- Calling `dns.setServers()` while a DNS query is in progress can cause the process to crash on a failed assertion [#894](https://github.com/iojs/io.js/issues/894)
# Community Updates
- [Tony Pujals](https://twitter.com/subfuzion) gave the io.js roadmap presentation to [BayNode](http://www.meetup.com/BayNode/events/220246228/). The video was posted to [vimeo](https://vimeo.com/121707989) on March 9. Slides are available for anyone to give at their [local meetup](ron.buell@rd.io).
- [Johan Bergström](https://github.com/jbergstroem) is working on getting a patch into [V8](https://codereview.chromium.org/990063002) on behalf of io.js to bring Solaris support back into the latest version
- [NodeUp Episode 84](http://nodeup.com/eightyfour) it's io.js update #1 with [Mikeal Rogers](https://github.com/mikeal), [Trevor Norris](https://github.com/trevnorris) and [Bradley Meck](https://github.com/bmeck)
- [Mikeal Rogers](https://github.com/mikeal) was interviewed for [Descriptive](http://descriptive.audio) podcast on an episoded called [We've Never Had This Many Active Contributors to Core Before](http://descriptive.audio/episodes/12)
- [Mark Wolfe](https://twitter.com/wolfeidau) gave a [talk about io.js](https://twitter.com/wolfeidau/status/575785856545378304) at [@melbjs](https://twitter.com/melbjs) meetup, slides are published [here](https://speakerdeck.com/wolfeidau/iojs-bringing-es6-to-the-node)
- [dockeri.co](http://dockeri.co/) now runs on io.js, you can see the announcement [here](https://twitter.com/wjblankenship/status/575867637680369665)
- [Node.js Advisory Board](https://nodejs.org/about/advisory-board/) are talking about the [io.js/Node.js reconcilitation proposal](https://github.com/iojs/io.js/issues/978), you can check the meeting minutes [here](https://github.com/joyent/nodejs-advisory-board/blob/master/meetings/2015-03-09/minutes.md#nodejsiojs-reconciliation-bb)
# Upcoming Events
- [NodeConf](http://nodeconf.com/) tickets are on sale, June 8th and 9th at Oakland, CA and NodeConf Adventure for June 11th - 14th at Walker Creek Ranch, CA
- [CascadiaJS](http://2015.cascadiajs.com/) tickets are on sale, July 8th - 10th at Washington State
- [NodeConf EU](http://nodeconf.eu/) tickets are on sale, September 6th - 9th at Waterford, Ireland

**Comment by julianduque** [comment] 2015-03-09 21:52
@jbergstroem is likely getting a patch into [V8](https://codereview.chromium.org/990063002) on behalf of io.js to bring Solaris support back into the latest version

**Comment by subfuzion** [comment] 2015-03-09 22:07
1.5.1 release 2015-03-9

**Comment by subfuzion** [comment] 2015-03-09 22:32
(DRAFT)

# io.js 1.5.1 Release

On Monday, March 9th, @rvagg released io.js [v1.5.0](https://iojs.org/dist/v1.5.1/). The complete change log can be found [on GitHub](https://github.com/iojs/io.js/blob/v1.x/CHANGELOG.md).

### Notable changes
- **tls**: The reported TLS memory leak has been at least partially resolved via various commits in this release. Current testing indicated that there _may_ still be some leak problems. Track complete progress at [#1075](https://github.com/iojs/io.js/issues/1075).
- **http**: Fixed an error reported at [joyent/node#9348](https://github.com/joyent/node/issues/9348) and [npm/npm#7349](https://github.com/npm/npm/issues/7349). Pending data was not being fully read upon an `'error'` event leading to an assertion failure on `socket.destroy()`. (Fedor Indutny) [#1103](https://github.com/iojs/io.js/pull/1103)

### Known issues
- Possible remaining TLS-related memory leak(s), details at [#1075](https://github.com/iojs/io.js/issues/1075).
- Windows still reports some minor test failures and we are continuing to address all of these as a priority. See [#1005](https://github.com/iojs/io.js/issues/1005).
- Surrogate pair in REPL can freeze terminal [#690](https://github.com/iojs/io.js/issues/690)
- Not possible to build io.js as a static library [#686](https://github.com/iojs/io.js/issues/686)
- `process.send()` is not synchronous as the docs suggest, a regression introduced in 1.0.2, see [#760](https://github.com/iojs/io.js/issues/760) and fix in [#774](https://github.com/iojs/io.js/issues/774)
- Calling `dns.setServers()` while a DNS query is in progress can cause the process to crash on a failed assertion [#894](https://github.com/iojs/io.js/issues/894)

# Community Updates
- [Tony Pujals](https://twitter.com/subfuzion) gave Mikeal's io.js presentation to [BayNode](http://www.meetup.com/BayNode/events/220246228/). The video was posted to [vimeo](https://vimeo.com/121707989) on March 9.

**Comment by rvagg** [comment] 2015-03-09 23:44
FYI, after releasing, updates in iojs/io.js#1075 indicate that the leak may actually be fixed, keep an eye on that issue but you may be able to announce that it's fixed even though the release notes hedge the language around it.

**Comment by yosuke-furukawa** [comment] 2015-03-10 15:25
NodeSource introduces Node.js v0.12 and io.js and their Linux Repositories.
https://nodesource.com/blog/nodejs-v012-iojs-and-the-nodesource-linux-repositories

**Comment by yosuke-furukawa** [comment] 2015-03-10 15:34
NodeUp#84 talks about io.js Update by @mikeal, @bradleymeck and @trevnorris! https://twitter.com/NodeUp/status/573256463440855040

**Comment by mikeal** [comment] 2015-03-10 16:50
I got interviewed for this podcast http://descriptive.audio/episodes/12

**Comment by mikeal** [comment] 2015-03-10 16:51
I think we should start to list upcoming _destination_ conferences that have tickets on sale. Both NodeConf and NodeConf.eu have tickets on sale right now :)

**Comment by rosskukulinski** [comment] 2015-03-10 17:50
It think also CascadiaJS?

**Comment by rosskukulinski** [comment] 2015-03-10 17:51
@yosuke-furukawa we listed that nodesource blog last week.

**Comment by julianduque** [comment] 2015-03-10 19:11
@mikeal also [JSConf Uruguay](https://jsconf.uy/) and [EmpireJS](http://2015.empirejs.org/) on April

**Comment by yosuke-furukawa** [comment] 2015-03-11 03:13
@rosskukulinski ooops. thanks. i removed my comment.

**Comment by julianduque** [comment] 2015-03-12 02:38
weekly update draft is on the first comment based on @tonypujals one, please review and comment :)

**Comment by yosuke-furukawa** [comment] 2015-03-12 11:27
node advisory board members are talking about io.js and node.js reconciliation. https://github.com/joyent/nodejs-advisory-board/blob/master/meetings/2015-03-09/minutes.md#nodejsiojs-reconciliation-bb

**Comment by mikeal** [comment] 2015-03-12 17:32
"http://dockeri.co  now uses @official_iojs! Many wows! Much excite!"

https://twitter.com/wjblankenship/status/575867637680369665

**Comment by mikeal** [comment] 2015-03-12 18:54
"Posted the slides for my @official_iojs talk last night at @melbjs https://speakerdeck.com/wolfeidau/iojs-bringing-es6-to-the-node"

https://twitter.com/wolfeidau/status/575785856545378304

**Comment by julianduque** [comment] 2015-03-13 14:19
I've sent the PR - please review/publish #44 :)

**Comment by subfuzion** [comment] 2015-03-13 16:41
Add to community updates (including @mikeal 's suggestions:
- io.js TC Meeting 2015-03-11 is available [here](https://www.youtube.com/watch?v=xXLnNSL0qvU)
- [NodeConf](http://nodeconf.com/) and [NodeConf EU](http://nodeconfeu.com/) tickets are on sale now

**Comment by Fishrock123** [comment] 2015-03-13 22:14
Looks like it's up at https://medium.com/@iojs/io-js-week-of-march-13th-e3024cc66802

But some of the headers seem at the wrong levels?

**Comment by alexpods** [comment] 2015-03-13 22:16
> io.js TC Meeting 2015-03-11 is available here

Meeting was skipped https://github.com/iojs/io.js/issues/1124 . Why it's published?

**Comment by julianduque** [comment] 2015-03-13 22:20
@alexpods you are right, updating article

**Comment by subfuzion** [comment] 2015-03-13 22:21
Adding the bullet was my fault; sorry about that @julianduque

**Comment by julianduque** [comment] 2015-03-13 22:26
@tonypujals @alexpods fixed :)

**Comment by alexpods** [comment] 2015-03-13 22:27
@julianduque :+1:

**Comment by jbergstroem** [comment] 2015-03-13 23:37
The v8 patch referenced in "community updates" landed upstream and we merged [yesterday](https://github.com/iojs/io.js/commit/8c4f0df464b82b424bc5f88ee9ece040c0f71581). We now have two buildbots provided by Joyent running tests. The next step is fixing the failing tests (a handful)!

**Closed as completed** 2015-03-15 23:43 UTC
Labels: weekly update

**Comment by julianduque** [comment] 2015-03-16 00:01
@jbergstroem thats good news, will add it to the next weekly update
