### ISSUE TITLE
Evangelism: Weekly Update April 24th

### ISSUE THREAD

**Issue by Gioyik** [nodejs/evangelism#64] opened 2015-04-17 19:39 UTC
What's next for the week bros!

**Comment by Gioyik** [comment] 2015-04-19 16:22
io.js v1.8.0 released. See it [here](https://github.com/iojs/io.js/blob/v1.x/CHANGELOG.md#2015-04-17-version-180-chrisdickinson)

**Comment by Gioyik** [comment] 2015-04-19 16:40
- Proposal to change the C HTTP parser JS HTTP parser [here](https://github.com/iojs/io.js/pull/1457)
- NPM founder talks about io.js at [InfoWorld](http://www.infoworld.com/article/2910594/node-js/npm-founder-foresees-merger-node-js-io-js.html)

**Comment by yosuke-furukawa** [comment] 2015-04-20 04:23
@Gioyik v1.8.0 is not released yet. see here: https://iojs.org/dist/

**Comment by yosuke-furukawa** [comment] 2015-04-20 04:31
We should wait to write the CHANGELOG in our weekly update until v1.8.0 release.
But I guess v1.8.0 will be released soon.

**Comment by yosuke-furukawa** [comment] 2015-04-20 04:36
@indutny asks a question about removing tls `newSession` and `resumeSession` event . see here: https://twitter.com/indutny/status/589330892813946880

And the issue is here https://github.com/iojs/io.js/issues/1462

**Comment by yosuke-furukawa** [comment] 2015-04-21 01:58
@Gioyik Yep, released. go ahead. https://iojs.org/dist/v1.8.1/

**Comment by Gioyik** [comment] 2015-04-21 18:50
Yes, seems that we will not have 1.8.0, instead will be 1.8.1.

**Comment by yosuke-furukawa** [comment] 2015-04-22 11:41
Add new TC members: mikeal, mscdex, shigeki
https://github.com/iojs/io.js/issues/1483#issuecomment-95128140

**Comment by julianduque** [comment] 2015-04-22 21:51
@Gioyik let's coordinate to have this published friday in the afternoon, sorry for being away but was caught in a lot of work

**Comment by rvagg** [comment] 2015-04-22 23:09
note that Jeremiah was the only new TC member added _today_. The others are vote-pending, Brian and Shigeki will join the TC in observer status for a few weeks at least before voting. Mikeal may be voted on sooner. But it's news-worthy still.

**Comment by Gioyik** [comment] 2015-04-23 01:39
@julianduque I am trying to automate everything. For example, I have programmed IFTTT to create an issue in evangelism repo every Friday for next weekly update week, so I don't forget it. I am trying to get more ways to automate the things. 

But, don't worry about it, all of us have lifes too, I will ping you by friday. Thanks for help us to get this done earlier.

**Comment by Gioyik** [comment] 2015-04-24 14:17
This issue is freeze now with the PR #66. If you have something to add for a weekly update, let's do it on #65.

**Comment by julianduque** [comment] 2015-04-25 01:41
Published and tweeted: https://twitter.com/official_iojs/status/591778312504135680

**Closed as completed by julianduque** 2015-04-25 01:41 UTC

**Comment by Gioyik** [comment] 2015-04-25 02:09
Thanks @julianduque
