### ISSUE TITLE
overly liberal artistic license with the pokéball design

### ISSUE THREAD

**Issue by timoxley** [nodejs/evangelism#39] opened 2015-03-07 12:38 UTC
Not sure how this happened but the official io.js pokéball might have employed a bit too much artistic license with its pokéball design:

![image](https://cloud.githubusercontent.com/assets/43438/6541278/437b6ba0-c502-11e4-9816-e46603982fa4.png)

Firstly I'd like to state I enjoy the adaption of the hexagonal shape to the pokéball, nice work, however – while this is instantly recognisable as a pokéball, I believe the overall design deviates a little too far from the canonical pokéball design, such that it very nearly looks as though it could be something else entirely, something from Digimon perhaps. We're in Pokéball uncanny valley country.

The most glaring problem with the design is that the white circle and the horizontal black line should be **horizontally & vertically centered**, rather than in their current positions towards the top and bottom of the pokéball. Also, it might seem like pedantry but a black line separating fields of red & white is one of the most recognizable pokéball aspects of all time – deferral to the non-standard off-white/cream in the bottom half of the io.js pokéball spoils the signature style. And look, I'm honestly not sure what's going on with that additional horizontal line at the top there – is that supposed to be the pokéball's mouth? I don't think pokéballs even have mouths. Maybe it's a pocket. A coin slot? I'm not sure, but it doesn't belong.

Top points for creativity and interpretation but overall it's a little too artsy and looks more like a knockoff pokéball that someone might sell from under his coat at the beach and I don't think that accurately reflects io.js values.

![image](https://cloud.githubusercontent.com/assets/43438/6541404/2e33a4dc-c508-11e4-989f-6486e8de0266.png)

**Comment by mikeal** [comment] 2015-03-07 18:01
I'm fairly certain this is a coincidence :)

**Comment by blakmatrix** [comment] 2015-03-07 19:44
I don't recognize this as a Pokemon reference, if anything, I thought when
chrome was released its logo looked like a Pokemon ball. I always thought
the Pokemon ball was a rip off of http://en.m.wikipedia.org/wiki/JezzBall

## 

Farrin A. Reid
http://www.linkedin.com/in/farrinreid

**Comment by mikeal** [comment] 2015-03-07 19:47
Everything is a pokeball if you stare at it long enough :P

**Comment by popomore** [comment] 2015-03-07 20:08
I tweet it few days ago.

https://twitter.com/popomore/status/573010705458180096

**Comment by rvagg** [comment] 2015-03-07 20:30
@mikeal & team: have you been collecting much feedback about the logo since it went live? I've been trying to be fairly silent about it because I'm no designer, but you know my opinions on it. Unfortunately, the feedback I've encountered both privately and publicly is almost universally negative&mdash;although that is from people with strong enough opinions to actually speak up, perhaps there are positives out there but they just aren't raving about it.

**Comment by mikeal** [comment] 2015-03-07 20:46
Most of the comments I've gotten have been "why is this different from the website?"

**Comment by mikeal** [comment] 2015-03-07 20:47
Oh no, that's not accurate, I had a bunch of positive comments on twitter when we first updated.

**Comment by mikeal** [comment] 2015-03-07 20:56
And for the record, I like this more than any reasonable alternative I've seen. Most of the favored logos in the logo thread, even many of the ones I like quite a bit, don't hold up under all the variations.

I don't think it's a good idea to try and collect feedback like this though. When Joyent rolled out the node.js logo it was universally hated. We were all pretty wrong considering that the whole hexagon thing came out of that logo. I have all kinds of new problems with the "official node.js logo" now that I've spent time to trying to use some of these designs in all the required contexts but my initial reaction, along with pretty much the entire community, was dead wrong.

**Comment by mikeal** [comment] 2015-03-07 20:59
Oh, I don't know if everyone has seen the full writeup on the treatement http://dffrnt.com/io/

**Comment by bnb** [comment] 2015-03-07 21:25
@timoxley I'd say with 98.98% certainty that the design was not based off of a poke-ball. The differences you noted as weird are weird only in context of it being based off a poke-ball. I suggest you read the treatment that @mikeal posted. Some points about the logo:
- The icon is based off of a basic rocket ship
  - The lower white, yellow, and orange colors are the flame powering the ship
  - As you can imagine, the porthole on a rocket ship typically isn't located on the border of the engine.
- Take a look at the circle (porthole) and the line below it. Can you imagine what they might be saying? I suggest turning your head 90° counter-clockwise, as that might help you see what it is.

**Comment by trevnorris** [comment] 2015-03-08 20:11
@bnb Regardless of how the design was intended, no one I've spoken with saw a rocket ship at initial inspection. While there were more than a few that expressed seeing the pokéball.

@mikeal I shouldn't have to read an article to try and understand the what and why of a logo. What I see is an incorrect linear gradient on the upper half. It blends out as if the light were pointing to a sphere, but the general hexagon shape should lead me to believe it's a icosahedron. Also the shading under the IO and on the belt do not match the point on the top left. The gradient is visually distracting.

**Comment by osslate** [comment] 2015-03-08 20:37
I first saw this through http://dffrnt.com/io. Had I not read through the article explaining the design process, I wouldn't have been able to understand the logo. Even after reading it, it doesn't make much sense to me. It didn't cross my mind that it looked like a pokéball, but I just can't see the resemblance to a rocket. I didn't get the "IO" part either, because of it being rotated 90º, and because the "I" seems thinner than the "O".

Logos should be be clear, I personally don't believe that this logo is great in that regard.

**Comment by mikeal** [comment] 2015-03-08 21:34
@trevnorris we mostly use the flat version without the gradients anyway.

None of this is actually helpful. Nobody has an alternative treatment nor the time and resources to implement it so I'm closing this thread until someone does.

**Closed as completed by mikeal** 2015-03-08 21:34 UTC

**Comment by trevnorris** [comment] 2015-03-08 23:10
@mikeal I feel it disingenuous to state none of what some was constructive feedback is helpful.

**Comment by bnb** [comment] 2015-03-08 23:46
@trevnorris I'm pretty sure he meant the feedback doesn't propose any alternatives - everybody would be happy to consider an alternative solution if one were to be presented, but right now that hasn't happened. I think he meant that it's "not helpful" in the sense that it's posing a problem that some people have and some people don't, without any course of action that can be considered the groups.

**Comment by timoxley** [comment] 2015-03-09 02:01
It probably just needs some adjustments to increase the "rocketness" and decrease the "pokeballness". Version without gradients doesn't increase rocketness. Once you figure out that it's a rocket, it's easier to not see the pokéball, but it definitely took me a number of **days** to "Ohhhh" realise it was a rocket.  I like the idea, I just don't think it's instantly recognisable as either a rocket or the letters IO enough.

**Comment by julianduque** [comment] 2015-03-09 03:20
I love the idea and concept behind the rocket but I need to be honest, at first glance it looks like a Pokeball, this is one of the best io.js logos but i'm with @timoxley, let's make it less pokeball and more rocket.

**Comment by bnb** [comment] 2015-03-09 03:35
@julianduque I don't think anybody has opposition to that. @vjk2005 is ultimately the one doing that work, and he's already doing a ton of work for us on his free time. I don't want to ask too much of him, and we haven't had _any_ other designers volunteer to help as far as I know, so I don't know how quickly we can iterate on this, if at all.

**Comment by vjk2005** [comment] 2015-03-09 05:55
Hi guys, I’m the designer of this logo concept. Just wanted to share the raw sketches so you can see the resemblance is purely unintentional.

While there were [60 odd concepts](http://dffrnt.com/io/) before this one, the “Explorers” concept began here with the splitting of the hexagon into a “body” and an “exhaust”
![photo on 09-03-15 at 9 50 am](https://cloud.githubusercontent.com/assets/2087804/6549990/a3cd72cc-c643-11e4-8db0-b48177af4ff8.jpg)

A few minutes later I had the idea of using the porthole as the “O” in IO and that stuck
![photo on 09-03-15 at 9 52 am 2](https://cloud.githubusercontent.com/assets/2087804/6549996/bbec65c0-c643-11e4-9499-7019a5426969.jpg)

I liked the idea of a “bubble” style shading with sharp highlights to make the rocket cute and approachable. I used this image as my shading reference (esp. the red pill)
![1 5](https://cloud.githubusercontent.com/assets/2087804/6550035/80b135b6-c644-11e4-8706-01c40b712b76.jpg)

First shading pass...
![first-shading-attempt](https://cloud.githubusercontent.com/assets/2087804/6550066/4b40959c-c645-11e4-9475-d06562e845a1.png)

Second shading pass...
![second-shading-pass](https://cloud.githubusercontent.com/assets/2087804/6550068/6f68b0b2-c645-11e4-834a-7521dbf3ec68.png)

I liked it and rolled it out as the final logo after removing the gloss which I felt was excessive.

To address some of the other points raised here:
- It’s possible to increase the rocket-ness at the risk of losing hexagon-ness. If anyone here has ideas to beat this constraint please post a rough sketch of your idea and I’ll create a finished version of it to replace the current logo. Before posting here, I tried my hand at a few variations but none of them look right.
- The “I” is thinner _by design_ and so is the orientation of the “IO”. The “IO” is meant to be _slightly_ harder to find, as a reward for enthusiasts who end up staring at the logo long enough (easter egg). People are supposed to see a rocket first and after a few exposures to the logo have a personal “A-ha! IO!” moment. It shouldn’t be too hard though or enough people won’t notice for it become a legend like the arrow in Fedex and the bear in Toblerone. I think the balance is good here but if people are not finding it often enough I can punch up the thickness of the “i” a tad and make the “IO” easier to spot.
- If the logo is at least one of these things — unique, memorable, controversial, conversation starter — it’s a success. With that in mind, I have a question: do the people you guys talk to who made the pokéball association view it as neutral or a negative? If it’s neutral and they were merely making an observation, that makes the logo a conversation starter and it’s a net positive for us. Even [negative reactions fade over time](http://www.wsj.com/articles/SB10001424052748704094304575029603030082186) so once they “see” the rocket it will replace the pokéball image and we are good.
- The easier we can make it for people to find the rocket the better it is for us, so ideas to make the rocket-ness stronger are most welcome. I’m currently focused on the website designs but I’ll circle back to the logo and make iterations between breaks. You can post your ideas here or email me (vijay@dffrnt).

(@bnb thanks for bringing me into the discussion.)

**Comment by trevnorris** [comment] 2015-03-09 16:33
@vjk2005 My main problem is that the main gradient is linear, while the shape of the hexagon in three dimensions would actually be a icosahedron. Leading it to feel more like a ball then anything else. And @mikeal's excuse of "we mostly use the flat version without the gradients anyway" just means that the "official" logo should not have that gradient.

**Comment by vjk2005** [comment] 2015-03-09 17:08
@trevnorris I haven’t actually used any icosahedrons in the design of the rocket. The hexagon profile comes from using the standard rocket body of a cone on a cylinder and hence the shading.
![no-icosahedrons](https://cloud.githubusercontent.com/assets/2087804/6559704/b0e4685a-c6aa-11e4-96e2-ecb7b338a444.png)

I suggest sticking with the gradient version. People will eventually get past the resemblance and the design should quickly start to grow on them. However, options like the flat version are there if we get lots of pushback from the community and have to dial the flourish down a bit.

Even so, I’ll keep tweaking the colors to see if something better comes along.

**Comment by trevnorris** [comment] 2015-03-09 17:14
@vjk2005 A gradient on a cylinder and cone is different then the gradient used on the logo. The gradient on the logo suggests that it's a sphere. The gradient on the logo shouldn't make it look like a sphere.

**Comment by vjk2005** [comment] 2015-03-09 17:21
@trevnorris if the gradients prove to be a deal-breaker, we can always switch to the flat version as the official logo.

**Comment by trevnorris** [comment] 2015-03-09 17:22
@vjk2005 that's great, and right now all I'm asking.

**Comment by timoxley** [comment] 2015-03-10 06:50
@vjk2005 never doubted that it was unintentional. 

>  do the people you guys talk to who made the pokéball association view it as neutral or a negative?

Negative.

> The easier we can make it for people to find the rocket the better it is for us, so ideas to make the rocket-ness stronger are most welcome.
> 
> It’s possible to increase the rocket-ness at the risk of losing hexagon-ness.

Agree this is a tricky issue. 
Perhaps doesn't need to be a perfect hexagon, maybe little chunks out of it here and there could work.
Perhaps appropriate background could fill in space.

![image](https://cloud.githubusercontent.com/assets/43438/6570389/9db24060-c734-11e4-8a47-dc4e015e9dbb.png)

Something that makes the nozzle more apparent would go a long way.
![image](https://cloud.githubusercontent.com/assets/43438/6570267/77527cca-c732-11e4-9ace-db2cd3a5255d.png)

Also perhaps a "it's definitely fire " treatment to the rocket exhaust plume. Hexagon constraint here reduces "fireness" as that's an unusual/very artificial overall shape for fire/rocket exhaust. 

![image](https://cloud.githubusercontent.com/assets/43438/6570345/e5a4f76a-c733-11e4-8521-6898b9577e07.png)

![image](https://cloud.githubusercontent.com/assets/43438/6570407/e26a4c7a-c734-11e4-9357-99e9f58ba365.png)

![image](https://cloud.githubusercontent.com/assets/43438/6570421/16a2d070-c735-11e4-84ed-01d1fcaee24d.png)

![image](https://cloud.githubusercontent.com/assets/43438/6570410/ea911e10-c734-11e4-8a47-77fd977e9a64.png)

Not suggesting it's totally wrong, I love the idea, just suggesting need to figure out what makes a rocket easily recognisable and try enhance that.

**Comment by vjk2005** [comment] 2015-03-10 19:43
Did some variations today based on the feedback here and this is one of the better ones that came out. Subtle gradients and smaller exhaust.
![logo-with-new-exhaust](https://cloud.githubusercontent.com/assets/2087804/6583662/8af2bce6-c78b-11e4-80e1-ed6ae3d61c12.png)

**Comment by rvagg** [comment] 2015-03-10 19:44
cyclops with a goatee?

**Comment by mikeal** [comment] 2015-03-10 19:47
I don't see the cyclops goatee in the latest one, something about the
colors and gradients. I think that might just be permanently stuck in your
head now though ;)

Also, cyclops with a goatee could be our new mascot ;) FreeBSD has a devil,
we have a f'ing cyclops with slight facial hair!

**Comment by rvagg** [comment] 2015-03-10 19:49
I'm down with that

**Comment by rvagg** [comment] 2015-03-10 19:51
![beep](https://cloud.githubusercontent.com/assets/495647/6583836/19444fea-c724-11e4-9806-96b74bec19f6.png)

**Comment by blakmatrix** [comment] 2015-03-10 20:15
I think the biggest issue with rocket logo as it is is that rockets generally aren't so short and thick. It looks sorta like a landing capsule but with a rocket exhaust. An Idea I had, but have no design skills, to maybe try would add some billowing smoke. I feel like if anyone is going to see a rocket it needs to be thinner or have indistingushable rocket features.

Tangentially, I am reminded of [@substack's image](http://substack.net/images/node_turtle.png).

**Comment by blakmatrix** [comment] 2015-03-10 20:24
As far as a thick and short rocket sorta fitting into what were going for I am reminded of this lamp. ![big boy rocket lamp](http://www.retroplanet.com/mm5/graphics/00000001/27827.jpg)

**Comment by pjbr** [comment] 2015-03-10 20:39
![MAD ROCKET SKILLZ IN PAINT](http://i.imgur.com/7YehHWw.png)

Decent rocket i made

**Comment by rvagg** [comment] 2015-03-10 20:47
now a full design _treatment_ please @pjbr

**Comment by dotproto** [comment] 2015-03-10 20:59
I took a stab at making @vjk2005's design a little more obvious as a rocket. I prefer the multiple flames over the single one. The single triangle in the center doesn't read as flame to me.

![thruster](https://cloud.githubusercontent.com/assets/1047763/6585177/7594f368-c72d-11e4-9a8e-1cb5ee480b7e.png)

**Comment by brycebaril** [comment] 2015-03-10 21:00
The sad robot's eye and mouth are not vertically centered, is this intentional?

**Comment by vjk2005** [comment] 2015-03-11 07:36
We have a winner.
![nailed-it](https://cloud.githubusercontent.com/assets/2087804/6592125/5e8b16a8-c7ef-11e4-875a-cd90cb4d78c8.png)

**Comment by blakmatrix** [comment] 2015-03-11 08:56
@vjk2005 I like that last one, a lot. Looks like a red pill - the io is now pronounced it seems (io, the red pill?), looks like a rocket on its way!

@rvagg I now see the cyclops with facial hair/fancy collar also...

**Comment by trevnorris** [comment] 2015-03-11 19:36
@vjk2005 Can you do another pass and make the red solid, with no gradient? Would like to see what it looks like. Thanks!

**Comment by vjk2005** [comment] 2015-03-11 21:14
@blakmatrix thanks : )

@trevnorris the gradients I've used this time are really subtle so there won't be much of a difference 
![nailed-it-flat](https://cloud.githubusercontent.com/assets/2087804/6606996/a6ba0444-c861-11e4-8fb0-ab3b1add40c6.png)

**Comment by trevnorris** [comment] 2015-03-11 22:01
@vjk2005 It is subtle, but IMO that looks awesome. Might try it having removed the drop shadow from the IO (it's lost anyways at small-ish resolutions), but I'm really digging it. Thanks for indulging my curiosity. :)

**Comment by julianduque** [comment] 2015-03-12 01:25
@vjk2005 looks awesome!!

**Comment by mikeal** [comment] 2015-03-12 17:01
This is great! Can we get updated twitter images so I can update?

**Comment by vjk2005** [comment] 2015-03-12 19:57
@trevnorris drop shadows are out the window in the latest set.

@mikeal PR sent : )

**Comment by mikeal** [comment] 2015-03-12 19:58
Twitter is updated.

**Comment by trevnorris** [comment] 2015-03-12 22:01
@vjk2005 awesome work. looks great.

**Comment by vjk2005** [comment] 2015-03-13 04:49
@trevnorris :+1:
