### ISSUE TITLE
Evangelism: Weekly Update April 24th

### ISSUE THREAD

**Issue by Gioyik** [nodejs/evangelism#61] opened 2015-04-17 08:02 UTC
It&rsquo;s Friday, Friday... Gotta get down on Friday!

**Comment by mikeal** [comment] 2015-04-17 17:29
Duplicate of  #55

**Closed as completed by mikeal** 2015-04-17 17:29 UTC

**Comment by Gioyik** [comment] 2015-04-17 17:31
@mikeal sorry, this issue is for next week not current. I named it bad.

**Comment by mikeal** [comment] 2015-04-17 17:34
Can we just rename the other one, it has all the content in it?

**Comment by Gioyik** [comment] 2015-04-17 19:07
@mikeal I open every Friday an issue for next week to collect info for weekly update. I named this issue accidentally as #55 but it not the same, #55 will close soon until the PR #63 is merged and published on Medium.

This issue is for the coming of 24th. Could be open again?

Sorry for the misunderstanding

**Comment by mikeal** [comment] 2015-04-17 19:13
OH I SEE! :)

Let's open a new one that doesn't have this history of us figuring out what this issue should be :)

**Comment by Gioyik** [comment] 2015-04-17 19:38
sure :)
